import Link from "next/link";
import { ArrowUpRight, Check, FileVideo, LockKeyhole, Sparkles } from "lucide-react";
import Analyzer from "@/components/Analyzer";

export default function Home() {
  const jsonLd = { "@context": "https://schema.org", "@type": "WebApplication", name: "ClipFetch", url: "https://clipfetch.in", description: "A clear, privacy-minded YouTube format analyzer and downloader.", applicationCategory: "MultimediaApplication", operatingSystem: "Web" };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><section className="grid-bg overflow-hidden"><div className="mx-auto max-w-6xl px-5 pb-20 pt-20 md:pb-28 md:pt-28"><div className="max-w-3xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-emerald-700/20 bg-mint/60 px-3 py-1 text-xs font-bold uppercase tracking-widest text-emerald-900"><Sparkles size={14} /> YouTube-only downloader</div><h1 className="text-5xl font-black leading-[.98] tracking-[-.06em] md:text-7xl">Save YouTube,<br /><span className="text-emerald-600">simply.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-ink/65">Analyze a public YouTube video before you download. ClipFetch shows available formats clearly and does not accept links from other sites.</p></div><div className="mt-12"><Analyzer /></div></div></section><section className="mx-auto max-w-6xl px-5 py-20"><div className="grid gap-5 md:grid-cols-3"><Feature icon={<FileVideo />} title="See formats first" text="Review the formats yt-dlp finds for the public YouTube video." /><Feature icon={<LockKeyhole />} title="Privacy-minded" text="No accounts, playlists, or frontend link history." /><Feature icon={<Check />} title="YouTube only" text="Strict URL validation rejects other domains and unsupported YouTube shapes." /></div><div className="mt-16 flex flex-col items-start justify-between gap-5 rounded-3xl bg-ink p-8 text-cream md:flex-row md:items-center md:p-12"><div><p className="text-2xl font-black">New here?</p><p className="mt-2 text-cream/60">Learn how ClipFetch handles a YouTube link in three simple steps.</p></div><Link href="/how-it-works" className="flex items-center gap-2 rounded-full bg-mint px-5 py-3 font-bold text-ink hover:bg-white">How it works <ArrowUpRight size={17} /></Link></div></section></>;
}
function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="rounded-2xl border border-ink/10 bg-white p-6"><div className="mb-5 flex h-10 w-10 items-center justify-center rounded-xl bg-mint text-emerald-800">{icon}</div><h2 className="text-lg font-bold">{title}</h2><p className="mt-2 leading-7 text-ink/60">{text}</p></div>; }
