"use client";
import { FormEvent, useState } from "react";
import { AlertCircle, ArrowRight, CheckCircle2, Loader2, Link2, ShieldCheck } from "lucide-react";
import { analyzeMedia, ApiError, downloadMedia, MediaAnalysis } from "@/lib/api";

export default function Analyzer() {
  const [url, setUrl] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<MediaAnalysis | null>(null);
  async function submit(e: FormEvent) { e.preventDefault(); setError(""); setResult(null); if (!/^https?:\/\/(www\.|m\.)?(youtube\.com|youtu\.be)\//i.test(url)) { setError("Paste a public YouTube watch, Shorts, embed, or youtu.be URL."); return; } setBusy(true); try { setResult(await analyzeMedia(url)); } catch (err) { setError(err instanceof ApiError ? err.message : "Something went wrong. Please try again."); } finally { setBusy(false); } }
  async function download(formatId: string, extension: string) { setError(""); setBusy(true); try { const blob = await downloadMedia(url, formatId); const href = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = href; anchor.download = `youtube-download.${extension}`; anchor.style.display = "none"; document.body.appendChild(anchor); anchor.click(); window.setTimeout(() => { URL.revokeObjectURL(href); anchor.remove(); }, 1_000); } catch (err) { setError(err instanceof ApiError ? err.message : "The download failed. Please try again."); } finally { setBusy(false); } }
  return <section id="analyze" className="mx-auto max-w-3xl px-5"><form onSubmit={submit} className="rounded-3xl border border-ink/10 bg-white p-3 shadow-xl shadow-ink/5"><div className="flex flex-col gap-3 sm:flex-row"><div className="flex flex-1 items-center gap-3 rounded-2xl bg-cream px-4"><Link2 size={19} className="text-ink/40" /><input aria-label="YouTube URL" value={url} onChange={e => setUrl(e.target.value)} placeholder="Paste a public YouTube URL" className="w-full bg-transparent py-4 outline-none placeholder:text-ink/40" /></div><button disabled={busy} className="flex items-center justify-center gap-2 rounded-2xl bg-emerald-600 px-6 py-4 font-bold text-white transition hover:bg-emerald-700 disabled:opacity-60">{busy ? <Loader2 className="animate-spin" size={19} /> : <>Analyze YouTube <ArrowRight size={18} /></>}</button></div></form>
    <p className="mt-3 flex items-center justify-center gap-2 text-center text-xs text-ink/50"><ShieldCheck size={14} /> YouTube links only. No account or link history. Save content you have permission to use.</p>
    {error && <div role="alert" className="mt-6 flex items-start gap-3 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertCircle size={18} className="mt-0.5 shrink-0" />{error}</div>}
    {result && <div className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-center gap-2 font-bold"><CheckCircle2 size={18} />{result.title}</div><p className="mt-1 text-sm text-ink/60">Download only content you are authorized to save and that YouTube permits.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{result.formats.map(f => <button disabled={busy} key={f.id} onClick={() => download(f.id, f.extension)} className="flex items-center justify-between rounded-xl border border-emerald-200 bg-white p-3 text-left text-sm hover:border-emerald-500 disabled:opacity-60"><span><b>{f.type.toUpperCase()}</b> · {f.quality ?? f.label}</span><span className="text-ink/50">{f.extension}</span></button>)}</div></div>}
  </section>;
}
